services:
  app:
    build: .
    container_name: todo-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todo_db 
      - JWT_SECRET=secret_A7a_000
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      db: 
        condition: service_healthy 
    volumes:
      - .:/app
      - /app/src/generated
      - /app/node_modules

  db: 
    image: postgres:15-alpine
    container_name: todo-postgres-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: